; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[admin_menu][subdir] = "contrib"
; projects[admin_menu][version] = "3.0-rc2"

projects[ctools][subdir] = "contrib"
; projects[ctools][version] = "1.0"

projects[devel][subdir] = "contrib"
; projects[devel][version] = "1.3"

projects[eck][subdir] = "contrib"
; projects[eck][version] = "2.0-beta1"

projects[entity][subdir] = "contrib"
; projects[entity][version] = "1.0-rc2"

projects[features][subdir] = "contrib"
; projects[features][version] = "1.0-rc2"

projects[jquery_update][subdir] = "contrib"
; projects[jquery_update][version] = "2.2"

; Themes
projects[mothership][subdir] = "mothership"
projects[mothership][version] = "2.8"


; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[devel_entity][download][type] = ""
; projects[devel_entity][download][url] = ""
; projects[devel_entity][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[ldh][download][type] = ""
; projects[ldh][download][url] = ""
; projects[ldh][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[svg_inpage][download][type] = ""
; projects[svg_inpage][download][url] = ""
; projects[svg_inpage][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; projects[views_slideshow__imageflow_advanced][download][type] = ""
; projects[views_slideshow__imageflow_advanced][download][url] = ""
; projects[views_slideshow__imageflow_advanced][type] = "module"
